# Generated by Django 3.0.3 on 2021-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='portrait',
            field=models.ImageField(default='images/portrait/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
