# Generated by Django 3.0.3 on 2021-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0002_auto_20210923_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1),
        ),
    ]
