# Generated by Django 3.0.3 on 2021-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0004_auto_20210923_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ImageField(default='images/portrait/default.png', upload_to='fuhaobang/tmplates/static/fuhaobang/images/portrait/'),
        ),
    ]
