# Generated by Django 3.0.3 on 2021-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0006_auto_20210923_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='portrait_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
