# Generated by Django 3.0.3 on 2021-09-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0007_person_portrait_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='person',
            name='brief_intro',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ImageField(default='images/portrait/default.png', upload_to='fuhaobang/static/fuhaobang/images/portrait/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait_url',
            field=models.CharField(default='', max_length=200, verbose_name='头像储存地址'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.IntegerField(default=-1, verbose_name='当前排名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wealth',
            field=models.CharField(max_length=200, verbose_name='身价'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件')),
                ('time', models.CharField(max_length=200, verbose_name='时间')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('brief_intro', models.TextField(verbose_name='简介')),
                ('attachment', models.CharField(choices=[('Empty', '无'), ('Image', '图片'), ('Video', '视频')], max_length=5, verbose_name='附件类型')),
                ('image', models.ImageField(default='images/event/default.png', upload_to='fuhaobang/static/fuhaobang/images/event/', verbose_name='图片')),
                ('video', models.FileField(default='images/video/default.mp4', upload_to='fuhaobang/static/fuhaobang/video/event/', verbose_name='视频')),
                ('attachment_url', models.CharField(default='', max_length=200, verbose_name='附件储存地址')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuhaobang.Person')),
            ],
        ),
    ]
