# Generated by Django 3.0.3 on 2021-09-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0008_auto_20210925_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attachment',
            new_name='attachment_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('brief_intro', models.TextField(verbose_name='简介')),
                ('link_type', models.CharField(choices=[('News', '新闻'), ('Book', '书籍'), ('Other', '其他')], max_length=5, verbose_name='附件类型')),
                ('image', models.ImageField(default='images/link/default.png', upload_to='fuhaobang/static/fuhaobang/images/link/', verbose_name='图片')),
                ('image_url', models.CharField(default='', max_length=200, verbose_name='图片储存地址')),
                ('link', models.CharField(max_length=300, verbose_name='链接')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuhaobang.Person')),
            ],
        ),
    ]
