# Generated by Django 3.0.3 on 2021-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0009_auto_20210925_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_time',
            field=models.CharField(default='1900', max_length=200, verbose_name='前端显示时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateField(blank=True, default='1900-01-01', verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(default='images/video/default.mp4', upload_to='fuhaobang/static/fuhaobang/videos/event/', verbose_name='视频'),
        ),
    ]
