# Generated by Django 3.0.3 on 2021-09-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuhaobang', '0010_auto_20210925_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attachment_url',
        ),
        migrations.RemoveField(
            model_name='link',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='person',
            name='portrait_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default=' ', max_length=200, verbose_name='地点'),
        ),
    ]
